OOP Basics Part II task3
olvo0157/GYK pull request #6
Opened 2022-11-27 12:33 UTC by olvo0157

2022-11-29 07:53 UTC, grkarolis requested changes

2022-11-29 07:53 UTC, grkarolis commented on task3/AtmApplication.java
> +        System.out.println("ATM balance: " + myBankAtm.getBalance());
Yra kodo vietu kurios kartojasi keleta kartu. Jas reiketu iskelti kaip atskirus metodus ir taip panaudoti. Nera gera praktika kartoti ta pati koda daug kartu. Jeigu taip atsitinka reiketu issikelti ta koda i atskira metoda.

2022-11-29 07:53 UTC, grkarolis commented on task3/Card.java
> +public abstract class Card extends Exception {
extends Exception sioje vietoje nera reikalingas

2022-11-29 07:53 UTC, grkarolis commented on task3/CreditCard.java
> +            throw new NotEnoughCreditException("Insufficient funds! Max available amount is: " + (getBalance() + credit) * (1 - interest / 100));
Skaiciavimas galetu buti kaip atskiras metodas, tam kad butu lengviau skaityti koda

2022-11-29 07:53 UTC, grkarolis commented on task3/CreditCard.java
> +        if (getBalance() + credit - amount * (1 + interest / 100) < 0) {
cia taip pat, galima issikelti i atskira metoda skaiciavima

2022-11-29 07:53 UTC, grkarolis commented on task3/MyBankAtm.java
> +            exc.printStackTrace(new java.io.PrintStream(System.out));
pakaktu tiesiog panaudoti System.out.println();

2022-11-30 05:45 UTC, olvo0157 commented on task3/AtmApplication.java
> +        System.out.println("ATM balance: " + myBankAtm.getBalance());
Supratau. Aciu!

2022-11-30 05:45 UTC, olvo0157 commented on task3/Card.java
> +public abstract class Card extends Exception {
ok

2022-11-30 06:08 UTC, olvo0157 commented on task3/CreditCard.java
> +        if (getBalance() + credit - amount * (1 + interest / 100) < 0) {
ok, aciu.

2022-11-30 06:12 UTC, olvo0157 commented on task3/MyBankAtm.java
> +            exc.printStackTrace(new java.io.PrintStream(System.out));
aciu

2022-11-30 06:25 UTC, merged